// <auto-generated />
using System;
using AgenciaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgenciaAPI.Migrations
{
    [DbContext(typeof(ReservaContext))]
    [Migration("20240110055206_TabelaUm")]
    partial class TabelaUm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AgenciaAPI.Model.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<long>("CPF")
                        .HasColumnType("bigint")
                        .HasColumnName("NumeroCpf");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime")
                        .HasColumnName("DataViagem");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("LocalDestino");

                    b.Property<string>("DestinoURL")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DestinoURL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NomeCompleto");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint")
                        .HasColumnName("NumeroTelefone");

                    b.Property<long>("Pessoas")
                        .HasColumnType("bigint")
                        .HasColumnName("QuantidadePessoas");

                    b.Property<double>("Valor")
                        .HasColumnType("double")
                        .HasColumnName("ValorPassagem");

                    b.HasKey("Id");

                    b.ToTable("reservas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPF = 9988890098L,
                            CheckIn = new DateTime(2024, 2, 19, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Destino = "Alagoas",
                            DestinoURL = "https://images.unsplash.com/photo-1625841028984-5a4c1a657e19?q=80&w=1473&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Nome = "Bruce Dickinson",
                            Numero = 81988880099L,
                            Pessoas = 4L,
                            Valor = 1.5820000000000001
                        },
                        new
                        {
                            Id = 2,
                            CPF = 88876543212L,
                            CheckIn = new DateTime(2024, 2, 10, 23, 58, 0, 0, DateTimeKind.Unspecified),
                            Destino = "Recife",
                            DestinoURL = "https://images.unsplash.com/photo-1612383892465-153167840470?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Nome = "Steve Harris",
                            Numero = 83977890000L,
                            Pessoas = 7L,
                            Valor = 1.6659999999999999
                        },
                        new
                        {
                            Id = 3,
                            CPF = 12354376598L,
                            CheckIn = new DateTime(2024, 2, 22, 17, 50, 0, 0, DateTimeKind.Unspecified),
                            Destino = "Paraiba",
                            DestinoURL = "https://images.unsplash.com/photo-1604978472078-5a067d2d0426?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Nome = "Adrian Smith",
                            Numero = 82977768896L,
                            Pessoas = 3L,
                            Valor = 1.288
                        },
                        new
                        {
                            Id = 4,
                            CPF = 9867823465L,
                            CheckIn = new DateTime(2024, 2, 15, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Destino = "Maranhão",
                            DestinoURL = "https://images.unsplash.com/photo-1663641023872-00b4cfae9751?q=80&w=1404&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Nome = "Nicko McBlain",
                            Numero = 78976556565L,
                            Pessoas = 6L,
                            Valor = 1.95
                        },
                        new
                        {
                            Id = 5,
                            CPF = 99777533101L,
                            CheckIn = new DateTime(2024, 2, 12, 20, 35, 0, 0, DateTimeKind.Unspecified),
                            Destino = "Natal",
                            DestinoURL = "https://images.unsplash.com/photo-1516242981651-2ee338449dea?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Nome = "Dave Murray",
                            Numero = 21988800987L,
                            Pessoas = 5L,
                            Valor = 1.4890000000000001
                        },
                        new
                        {
                            Id = 6,
                            CPF = 87699088765L,
                            CheckIn = new DateTime(2024, 2, 18, 22, 45, 0, 0, DateTimeKind.Unspecified),
                            Destino = "Sergipe",
                            DestinoURL = "https://images.unsplash.com/photo-1573484770405-d78bb704e7db?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Nome = "Janick Gers",
                            Numero = 11988890987L,
                            Pessoas = 3L,
                            Valor = 1.899
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
